spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/devfund?useSSL=false
    username: root
    password:
  mvc:
   view:
    prefix: /webPages/
    suffix: .jsp
